chore: tweaks

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -6,7 +6,7 @@ permissions:
 
 on:
   repository_dispatch:
-    types: [generate]
+    types: [generate, release]
   workflow_dispatch:
     inputs:
       openapi_url:
@@ -23,6 +23,10 @@ jobs:
           if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
             if [ -z "${{ github.event.client_payload.openapi_url }}" ]; then
               echo "Error: 'openapi_url' is missing in client_payload."
+              exit 1
+            fi
+            if [ "${{ github.event.action }}" == "release" ] && [ -z "${{ github.event.client_payload.version }}" ]; then
+              echo "Error: We are supposed to release, but 'version' is missing in client_payload."
               exit 1
             fi
           
@@ -56,5 +60,6 @@ jobs:
           branch: generator
           delete-branch: 'true'
           title: 'Generated API update'
+          body: 'Update of the client library using OpenAPI from: ${{ env.OPENAPI_URL }}'
           commit-message: 'Generated API update'
 
